-- DB tables > 1M
SELECT OWNER, table_name, segment_type, TRUNC (sum (bytes) / 1048576) "SIZE(1M)"
FROM
(SELECT OWNER, SEGMENT_NAME table_name, segment_type, bytes
 FROM SYS.DBA_SEGMENTS
 WHERE SEGMENT_TYPE like 'TABLE%'
 UNION ALL
 SELECT s.OWNER, i.TABLE_NAME, s.SEGMENT_TYPE, s.BYTES
 FROM SYS.DBA_INDEXES i, SYS.DBA_SEGMENTS s
 WHERE s.SEGMENT_NAME = i.INDEX_NAME
  AND  s.OWNER = i.OWNER
  AND  s.SEGMENT_TYPE like 'INDEX%'
  UNION ALL
 SELECT s.OWNER, l.TABLE_NAME, s.SEGMENT_TYPE, s.BYTES
 FROM SYS.DBA_LOBS l, SYS.DBA_SEGMENTS s
 WHERE s.SEGMENT_NAME = l.SEGMENT_NAME
  AND  s.OWNER = l.OWNER
  AND  s.SEGMENT_TYPE = 'LOBSEGMENT'
 UNION ALL
 SELECT s.OWNER, l.TABLE_NAME, s.SEGMENT_TYPE, s.BYTES
 FROM SYS.DBA_LOBS l, SYS.DBA_SEGMENTS s
 WHERE s.SEGMENT_NAME = l.INDEX_NAME
  AND  s.OWNER = l.OWNER
  AND  s.SEGMENT_TYPE = 'LOBINDEX'
 )
WHERE OWNER NOT IN ('SYS', 'ORDSYS')
GROUP BY OWNER, TABLE_NAME, SEGMENT_TYPE
HAVING TRUNC (SUM(bytes) / 1048576) > 0
ORDER BY SUM (bytes) DESC
